name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update Repository README Statistics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          ### For Content
          SHOW_TITLE: true
          SECTION_NAME: waka
          BLOCKS: ->
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_MASKED_TIME: false
          STOP_AT_OTHER: true
          # # For Commit
          # COMMIT_MESSAGE: Updated Waka-readme graph with new metrics
          # TARGET_BRANCH: main
          # TARGET_PATH: README.md
          # COMMITTER_NAME: GitHubActionBot
          # COMMITTER_EMAIL: action-bot@github.com
          # AUTHOR_NAME: Mukesh Kumar
          # AUTHOR_EMAIL: devsofmukesh@gmail.com